import {
  Bot,
  CheckCircle2,
  CircleHelp,
  ClipboardList,
  Database,
  Eye,
  GitMerge,
  Search,
  ShieldCheck,
  TriangleAlert,
  Truck,
  Users,
  UserCog,
} from "lucide-react";
import type { IAFlowTreeNode } from "./types";

export const IA_DEV_FLOW_TREE: IAFlowTreeNode = {
  id: "q",
  title: "Consulta",
  subtitle: "RRHH / HHGG",
  icon: Search,
  tone: "bg-green-500/95",
  position: { x: 60, y: 250 },
  children: [
    {
      id: "gpt",
      title: "OpenAI",
      subtitle: "Orquestador GPT",
      icon: Bot,
      tone: "bg-sky-500/95",
      position: { x: 240, y: 140 },
      children: [
        {
          id: "route",
          title: "Decidir",
          subtitle: "General o BD",
          icon: CircleHelp,
          tone: "bg-cyan-500/95",
          position: { x: 430, y: 140 },
          linksTo: ["result"],
          children: [
            {
              id: "meta",
              title: "Consultar",
              subtitle: "Metadatos",
              icon: Database,
              tone: "bg-orange-500/95",
              position: { x: 260, y: 250 },
              children: [
                {
                  id: "aus",
                  title: "Leer",
                  subtitle: "Ausentismos",
                  icon: ClipboardList,
                  variant: "detached",
                  tone: "bg-transparent",
                  position: { x: 470, y: 70 },
                  children: [
                    {
                      id: "join",
                      title: "Cruce por",
                      subtitle: "Cedula / Fecha",
                      icon: GitMerge,
                      tone: "bg-yellow-500/95",
                      position: { x: 620, y: 250 },
                      children: [
                        {
                          id: "rules",
                          title: "Aplicar",
                          subtitle: "Reglas",
                          icon: ShieldCheck,
                          tone: "bg-green-600/95",
                          position: { x: 620, y: 360 },
                          children: [
                            {
                              id: "check",
                              title: "Cumple?",
                              subtitle: "Validacion",
                              icon: CircleHelp,
                              tone: "bg-gray-700/95",
                              position: { x: 620, y: 460 },
                              children: [
                                {
                                  id: "alert",
                                  title: "Generar",
                                  subtitle: "Alerta",
                                  icon: TriangleAlert,
                                  tone: "bg-red-500/95",
                                  position: { x: 430, y: 560 },
                                },
                                {
                                  id: "audit",
                                  title: "Auditoria",
                                  subtitle: "Validacion",
                                  icon: Eye,
                                  tone: "bg-violet-500/95",
                                  position: { x: 760, y: 560 },
                                  linksTo: ["alert"],
                                  children: [
                                    {
                                      id: "result",
                                      title: "Generar",
                                      subtitle: "Resultado",
                                      icon: CheckCircle2,
                                      tone: "bg-green-500/95",
                                      position: { x: 980, y: 560 },
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              id: "personal",
              title: "Leer",
              subtitle: "Personal",
              icon: Users,
              variant: "detached",
              tone: "bg-transparent",
              position: { x: 630, y: 70 },
              linksTo: ["join"],
            },
            {
              id: "transport",
              title: "Leer",
              subtitle: "Transporte",
              icon: Truck,
              variant: "detached",
              tone: "bg-transparent",
              position: { x: 790, y: 70 },
              linksTo: ["join"],
            },
            {
              id: "operacion",
              title: "Leer",
              subtitle: "Operacion",
              icon: UserCog,
              variant: "detached",
              tone: "bg-transparent",
              position: { x: 950, y: 70 },
              linksTo: ["join"],
            },
          ],
        },
      ],
    },
  ],
};
