name: Check PR Source Branch
on:
  pull_request:
    branches:
      - main # Se activa cuando el destino es main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify that the source is develop
        run: |
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "Error: Solo se permiten Pull Requests a 'main' desde la rama 'develop'."
            exit 1
          fi
